### PR TITLE
Implimented ENV swapped old urls

### PR DESCRIPTION
**Pull request by Mcray3000**
## Changes
`Converted Backend and Frontend URLS to .env Vars`
New .env
```
BACKEND_URL='https://three07-mydiary-nibble.onrender.com'
FRONTEND_URL='https://scribbleandnibble.vercel.app'
```
Let me know if I missed any URLs in the code

## Reason
We should be able to set up our own local tests by changing these URLs in our env to local host

### CODE REVIEW

**Review by J-Dees — APPROVED** [review]

**Review by TLMatthies — APPROVED** [review]
<3

**Comment by eamyzzaj** [comment]
The code spelled _implemented_ wrong.

**Review by eamyzzaj — APPROVED** [review]
Looks good. Thanks for providing this fix so we can get back to local testing.

**Comment by Alaxxn** [comment]
Amazing! This genuinely makes my life significantly better. Thanks.

**Pull request merged**
