### PR TITLE
Added a login authentication.

### PR DESCRIPTION
**Pull request by TLMatthies**
The jwt is not stored yet, so you  can only check if login works, does not keep the user authenticated. Can't test locally, so this is a pull request to test.

### CODE REVIEW

**Comment by J-Dees** [comment]
# Pull Request #66 Review:
1. The code in backend.js and MyApp.js looks good, we still need to test this in our deployment and then move on to storing the jwt for user authentication
2. Consider removing the other file changes, from what I can tell they do not change anything so there is no reason to commit changes to them

**Comment by Mcray3000** [comment]
Okay, next time let workflow format

**Review by J-Dees — APPROVED** [review]

**Comment by TLMatthies** [comment]
> Okay, next time let workflow format

Will do

**Review by eamyzzaj — APPROVED** [review]
Looks good! I will point out that **handelDateClick** is misspelled in the code, but not an issue. Just pointing out for when trying to find later for any potential errors.

**Review by Mcray3000 — APPROVED** [review]
k

**Comment by TLMatthies** [comment]
> Looks good! I will point out that **handelDateClick** is misspelled in the code, but not an issue. Just pointing out for when trying to find later for any potential errors.

Alright, will look for in future. This is a temp to be able to test the login.

**Pull request merged**
